[project]
name = "taxi-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.0",
    "dj-rest-auth>=5.0.2",
    "django==6.0",
    "djangorestframework>=3.16.1",
    "load-dotenv>=0.1.0",
    "psycopg2-binary>=2.9.11",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
